title = "rpep.dev"
baseURL = "https://rpep.dev"
languageCode = "en-gb"
theme = ["gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-741QBT86P9"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "rpep.dev"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Ryan Pepper"
  favicon = ""
  site_logo = ""
  description = "Scientific software musings..."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-moon-gray"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/ryanpepper"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/rpep"
