title = "rpep.dev"
baseURL = "https://rpep.dev"
languageCode = "en-gb"
theme = ["rpep"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
googleAnalytics = "G-741QBT86P9"
enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    title = "rpep.dev"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Ryan Pepper"
  favicon = ""
  site_logo = ""
  description = "Scientific software musings..."
  recent_posts_number = 5

[[params.ananke_socials]]
name = "github"
url = "https://github.com/rpep"

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
